name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Clean Playwright Cache
      run: rm -rf ~/.cache/ms-playwright
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Check installed browsers
      run: ls -R ~/.cache/ms-playwright
    - name: Run Playwright tests
      run: npx playwright test tests/repracticingAllConceptsofPlayWright
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30