name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Clean Playwright cache (optional but helpful)
      run: rm -rf ~/.cache/ms-playwright

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: List installed browser binaries (debug step)
      run: ls -R ~/.cache/ms-playwright

    - name: Run All UI Test Cases
      run: npm run alluicases
