# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Install Node.js
- task: UseNode@2
  inputs:
    version: '16.x' # Use the Node.js version compatible with your project

# Step 2: Install dependencies
- script: |
    npm install
  displayName: 'Install dependencies'

# Step 3: Run Playwright tests
- script: |
    npx playwright install
    npx playwright test
  displayName: 'Run Playwright tests'

# Step 4: Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results/*.xml' # Adjust path if needed
    testRunTitle: 'Playwright Test Results'

# Step 5: Publish Playwright report
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'playwright-report' # Ensure this matches your Playwright report folder
    artifactName: 'playwright-report'
    publishLocation: 'Container'
